### PR TITLE
Adding default value to configDir 

### LINKED ISSUE #200: Server includes are not copied over from the src to the build folder
My server config includes another file, like so:

```
<include location="serverInclude.xml" />
```

When the Gradle project is cleaned and re-built, the included file is not 'copied' over to build, so the server config is in error.

### PR DESCRIPTION
**Pull request by jjvilleg**
Config Dir now has a default value. Fixes #200

### CODE REVIEW

**Comment by aguibert** [comment]
@jjvilleg @cherylking can this PR be reviewed/merged please?

**Comment by cherylking** [comment]
@aguibert This doesn't resolve the issue you just opened related to defaultValue for variables. I don't know that we want to merge this PR considering all the changes we need to make for 3.x.

**Comment by aguibert** [comment]
Yes, I understand it doesn't resolve the other NPE bug that I opened earlier, but before I thought we had reached a resolution and this change was good to go. If it's being deferred to 3.X that's fine, but looking back at this issue there wasn't any indication if it was intentionally waiting or forgotten about

**Comment by cherylking** [comment]
The changes from https://github.com/OpenLiberty/ci.gradle/pull/340 supersede this PR. Closing.

**Pull request closed without merging**
